import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { FlashToast } from "@/components/FlashToast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    apple: '/logo.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased min-h-screen bg-linear-to-b from-blue-100 to-white`}
      >
        <Toaster
          position="top-right"
          richColors
          closeButton
          expand
          toastOptions={{
            duration: 3500,
            className: "sajilofix-toast",
            style: {
              padding: "14px 16px",
              fontSize: "15px",
              borderRadius: "14px",
              minWidth: "340px",
            },
          }}
        />
        <FlashToast />
        {children}
      </body>
    </html>
  );
}
